version: '3'

volumes:
  production_traefik: {}

services:
  fastapi: &fastapi
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: fastapi_app_local
    container_name: fastapi
    env_file:
      - ./.envs/.local/.fastapi
    ports:
      - "80:80"
