version: '3'

services:
  fastapi: &fastapi
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: fastapi_app_local
    container_name: fastapi
    env_file:
      - ./.envs/.local/.fastapi
    ports:
      - "8000:8000"    
