version: '3'

volumes:
  production_traefik: {}

services:
  fastapi: &fastapi
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: fastapi_app_local
    container_name: fastapi
    env_file:
      - ./.envs/.local/.fastapi
    ports:
      - "80:80"

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: fastapi_app_production_traefik
    depends_on:
      - fastapi
    volumes:
      - production_traefik:/etc/traefik/acme:z

    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
